services:
  webapp:
    build: .
    container_name: aspnet_app
    ports:
      - ":80"
      - "8080:8080"
      - "8081:8081" 
    depends_on:
    - sqlserver
    environment:
      ConnectionStrings__Connection: Server=sqlserver;Database=ProjetoClaro;User Id=sa;Password=passPadrao123;TrustServerCertificate=true;
    networks:
      - appnet

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "passPadrao123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - appnet

volumes:
  sql_data:

networks:
  appnet:

